name: タスク
description: プロジェクトのタスクを作成する
title: "[タスク]: "
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## タスク作成フォーム
        タスクの詳細を入力してください。明確な説明があるとチームの協働が円滑になります。
        実装を伴う機能のリクエストや、バグの報告は別のテンプレートをご利用ください。
        本テンプレートはプログラムの実装や修正を伴わないタスクの作成にご利用ください。

  - type: input
    id: task-title
    attributes:
      label: タスク概要
      description: タスクを一言で説明してください
      placeholder: "ドキュメント更新"
    validations:
      required: true
      
  - type: dropdown
    id: task-category
    attributes:
      label: カテゴリ
      description: タスクの種類を選択してください
      options:
        - 管理業務
        - ドキュメント作成/更新
        - レビュー
        - 調査/リサーチ
        - 会議/ミーティング
        - テスト/QA
        - その他
    validations:
      required: true

  - type: dropdown
    id: task-priority
    attributes:
      label: 優先度
      description: このタスクの優先度を選択してください
      options:
        - 高（緊急）
        - 中（通常）
        - 低（余裕があれば）
    validations:
      required: false

  - type: dropdown
    id: task-size
    attributes:
      label: 作業量
      description: このタスクの作業量を選択してください
      options:
        - 小（1時間以内）
        - 中（半日程度）
        - 大（1日以上）
    validations:
      required: false

  - type: textarea
    id: task-details
    attributes:
      label: 詳細内容
      description: タスクの詳細と完了条件を記入してください
      placeholder: |
        - 実施内容：
        - 完了条件：
    validations:
      required: true

  - type: input
    id: task-related
    attributes:
      label: 関連Issue
      description: 関連するIssueがあれば番号を記入
      placeholder: "#123"
    validations:
      required: false

  - type: checkboxes
    id: task-flags
    attributes:
      label: フラグ
      description: 該当する項目をチェックしてください
      options:
        - label: サポートが必要
        - label: レビューが必要
        - label: ブロッカーあり
        - label: 急ぎ対応
    validations:
      required: false